version: '3'

services:

  postgres:
    env_file:
      - ".env"
    image: "postgres:12.3-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  server:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "fourpartsweb.app:create_app()"
    depends_on:
      - "postgres"
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    volumes:
      - ".:/fourpartsweb"

volumes:
  postgres: {}
        